### PR TITLE
chore: remove cruft, add a test

### PR DESCRIPTION
**Pull request by meyer**
- I ran `yarn prettier --write "**/*.{ts,md}"`
- I consolidated the three base tsconfigs down into one, `tsconfig.base.json`
- I removed the errant `.editorconfig copy`
- I deleted `tslint.json` since the project uses eslint
- I removed `.npmignore` in favour of a `files` entry in `package.json` containing just `"dist"`
- I updated the `engines` entry in `package.json` to `7.5.0` to match the minimum node version that TypeScript’s output supports
- I added a test that outputs a list of the files that will be published to NPM.

### CODE REVIEW

**Comment by baltedewit** [comment]
Thanks for the great PR! I would love to merge this but the linting/formatting step appears to have changed the CHANGELOG.MD which is an automatically generated file (by standard-version) and I'm not sure how well that will work. Worst case scenario it could block the CI from doing an automated release, I guess. I think it would be okay to simply have this one ignored?

**Comment by meyer** [comment]
@baltedewit ah good to know. I’ll add `CHANGELOG.md` to `.prettierignore`

**Comment by meyer** [comment]
Even better: I just saw that `standard-version` has lifecycle scripts that let you hook into different phases of the version bumping. I added one for `postchangelog` that runs prettier on `CHANGELOG.md`.

**Comment by baltedewit** [comment]
Thanks for that and just as a heads up: your version of yarn appears to resolve some packages to "artifacts.twitter.biz" which does not appear to be publicly available.

**Comment by meyer** [comment]
@baltedewit ugh, sorry about that. Work machine 😩 Did the CI check actually pass, or is CI not running on PRs?

**Comment by baltedewit** [comment]
CI was not configured to run on PR's at first, future PR's should be ran though.

CI is currently failing on vulnerabilities check, that would require the resolutions like these: https://github.com/nrkno/tv-automation-state-timeline-resolver/blob/master/package.json#L153

I've not looked into it further but I do get some linting and compile errors in my local setup

**Pull request merged**
